### ISSUE TITLE
Use resources instead of defining routes manually

### ISSUE THREAD

**Issue by webbedfooty** [webbedfooty/howlr-rails#3]

**Comment by gdavida** [comment]
Prefix Verb   URI Pattern                Controller#Action
   wolves GET    /wolves(.:format)          wolves#index
          POST   /wolves(.:format)          wolves#create
 new_wolf GET    /wolves/new(.:format)      wolves#new
edit_wolf GET    /wolves/:id/edit(.:format) wolves#edit
     wolf GET    /wolves/:id(.:format)      wolves#show
          PATCH  /wolves/:id(.:format)      wolves#update
          PUT    /wolves/:id(.:format)      wolves#update
          DELETE /wolves/:id(.:format)      wolves#destroy
    howls GET    /howls(.:format)           howls#index
          POST   /howls(.:format)           howls#create
 new_howl GET    /howls/new(.:format)       howls#new
edit_howl GET    /howls/:id/edit(.:format)  howls#edit
     howl GET    /howls/:id(.:format)       howls#show
          PATCH  /howls/:id(.:format)       howls#update
          PUT    /howls/:id(.:format)       howls#update
          DELETE /howls/:id(.:format)       howls#destroy
